name: trys mudford. front-end developer.
markdown: redcarpet
pygments: true
permalink: :title
category_dir: categories
timezone: Europe/London
category-list: [usability, rwd, css, javascript, web, snippets]